import type { Metadata } from "next";
import CaseSection from "@/components/case-study/CaseSection";
import CaseStudyLayout from "@/components/case-study/CaseStudyLayout";
import TodoNote from "@/components/case-study/TodoNote";
import ImageFrame from "@/components/ImageFrame";
import PullQuote from "@/components/PullQuote";
import VideoFrame from "@/components/VideoFrame";

export const metadata: Metadata = {
  title: "My World — Designing an AI That Remembers You Back",
  description:
    "End-to-end design of the COROS AI surface that reflects a user's coaching history back to them — information architecture, widgets, and the LLM prompts behind every card.",
};

const TOC = [
  { id: "problem", label: "The problem" },
  { id: "hard", label: "What made this hard" },
  { id: "architecture", label: "Layer 1: Architecture" },
  { id: "interface", label: "Layer 2: Interface" },
  { id: "ai", label: "Layer 3: The AI" },
  { id: "implementation", label: "Co-implementation" },
  { id: "outcomes", label: "Where it stands" },
  { id: "takeaway", label: "The takeaway" },
];

export default function MyWorld() {
  return (
    <CaseStudyLayout
      slug="my-world"
      eyebrow="COROS AI · Case Study"
      title="My World — Designing an AI That Remembers You Back"
      summary="A page that reflects a user's coaching history back to them — designed from the information architecture to the prompts that generate every card."
      meta={[
        {
          label: "Role",
          value: "Product Designer — design, prompt engineering, prototyping, co-implementation",
        },
        { label: "Team", value: "Founder/CEO, 3 engineers, 2 designers" },
        {
          label: "Timeline",
          value: (
            <>
              <TodoNote>fill in duration</TodoNote> 2026 — in progress, shipping
              incrementally
            </>
          ),
        },
        {
          label: "Tools",
          value:
            "Figma, Claude Code, Streamlit, HTML/CSS/JS prototyping, LLM prompt engineering (Gemini 2.5 Flash via LiteLLM)",
        },
      ]}
      toc={TOC}
    >
      <CaseSection id="problem" eyebrow="The problem" title="Coaching that evaporates">
        <p>
          COROS is an AI life coach. Users have genuinely transformative conversations —
          they name a fear, make a commitment, see something about themselves for the
          first time. Then the session ends and all of it disappears into chat history.
        </p>
        <p>
          My World is the answer: a page that reflects a user&rsquo;s coaching history
          back to them. The design brief I wrote for it became the team&rsquo;s north
          star:
        </p>
        <PullQuote attribution="The design brief, and the team's north star">
          A mirror, not a filing cabinet.
        </PullQuote>
        <p>
          Not a productivity tracker, not a stats dashboard — a surface that shows you
          the pattern of your own transformation and invites you back into conversation.
          That one sentence ended up settling dozens of downstream debates: no page-level
          filters, no scores or streaks, a ~100-word cap per widget, and every element
          ending in an on-ramp back to coaching (Continue, Revisit, New conversation).
        </p>
      </CaseSection>

      <CaseSection id="hard" eyebrow="The challenge" title="What made this hard">
        <p>
          This wasn&rsquo;t a UI project with an API behind it. The content of every card
          is <strong>generated by LLM prompts I wrote</strong> — so the design and the
          intelligence had to be built together. A beautiful breakthrough card is
          worthless if the model hallucinates breakthroughs. I ended up owning three
          layers at once:
        </p>
        <ol>
          <li>
            <strong>The information architecture</strong> — how raw conversations become
            structured, browsable objects
          </li>
          <li>
            <strong>The interface</strong> — a responsive web + mobile page of
            independent widgets
          </li>
          <li>
            <strong>The prompts</strong> — the generation layer that fills every field on
            screen, plus the QA tooling to test it
          </li>
        </ol>
      </CaseSection>

      <CaseSection
        id="architecture"
        eyebrow="Layer 1 · Architecture"
        title="Sessions → Topics → My World"
      >
        <p>
          I co-authored the product&rsquo;s design and implementation document through
          four versions (v1 → v4), which the engineering team builds directly from. Its
          foundational distinction: a <strong>Session</strong> is an event (one
          conversation, factually summarized); a <strong>Topic</strong> is a territory (a
          situation in your life that sessions keep returning to — &ldquo;Navigating a
          difficult conversation with dad,&rdquo; &ldquo;The job search&rdquo;).
        </p>
        <p>
          The hardest rule I fought for:{" "}
          <strong>a topic is a situational territory, never a feeling.</strong> Early
          model outputs kept producing topics like &ldquo;Self-worth&rdquo; and
          &ldquo;Avoiding conflict&rdquo; — psychologically flattering, navigationally
          useless, and subtly harmful (nobody wants their anxiety enshrined as a
          permanent folder). I codified this as the <em>identity-vs-texture</em> rule:
          feelings may color a topic&rsquo;s summary, but the title and organizing
          identity is always the situation. This rule now lives in the topic prompts and
          the detection pipeline (embedding search at a tuned threshold → LLM match
          decision).
        </p>
        <p>
          I also designed My World as a <strong>federated portal</strong>: each widget is
          engineered and launched independently with its own prompt, logic, and
          documented rationale. At a pre-seed startup this was a shipping strategy as
          much as a design one — engineers could build the Reminders widget without
          waiting on the Provocation prompt to stabilize.
        </p>
      </CaseSection>

      <CaseSection
        id="interface"
        eyebrow="Layer 2 · Interface"
        title="Three iterations that mattered"
      >
        <h3>Establishing the top level</h3>
        <p>
          The first structural decision was the page itself: a <strong>featured band</strong>{" "}
          of three reflective cards (My Breakthroughs, Coaching Provocation, Latest
          Breakthrough) above a full-width stacked <strong>Topics list</strong>,
          filterable by the seven life dimensions (Family, Work, Self, Health, Meaning,
          Belonging, World) and by status (Active / Snoozed / Archived). Topics are never
          tiled as a grid — each gets room to breathe, because a topic is a respected
          territory, not a search-history tile.
        </p>
        <p>
          A cross-page filtering concept (click a dimension, everything filters) tested
          well in principle — but I argued to defer it out of v1 and hold a stricter
          rule: <strong>filters belong to individual widgets, not the page.</strong> That
          constraint paid off later in an unexpected way.
        </p>
        <VideoFrame
          title="My World, top to bottom"
          description="A tour of the page: the featured band of reflective cards above the stacked topics list, filtered by dimension and status."
          src="/videos/my-world/page-tour.mp4"
          tone="lavender"
        />

        <h3>Merging the donut and the Latest Breakthrough</h3>
        <p>
          We had two separate widgets: a donut chart counting breakthroughs by dimension,
          and a card showing the most recent breakthrough. The donut was under threat —
          half the team leaned toward replacing it with a line chart, and a mockup
          decision was pending on me.
        </p>
        <p>
          Instead of choosing between them, I merged them into{" "}
          <strong>one widget with two modes</strong>, and specced the full state machine:
        </p>
        <ul>
          <li>
            <strong>Mode A (default):</strong> donut inert, panel shows the globally
            newest breakthrough, arrows walk the entire history chronologically.
          </li>
          <li>
            <strong>Mode B (segment clicked):</strong> panel filters to that dimension;
            arrows traverse a flat list built from all non-empty dimensions in
            color-wheel palette order, newest→oldest within each;{" "}
            <strong>
              auto-advance across a dimension boundary moves the donut&rsquo;s live
              selection in real time.
            </strong>{" "}
            Click outside to exit; reload always restores Mode A.
          </li>
        </ul>
        <p>
          I resolved every edge case before handoff — backward symmetry (stepping before
          a dimension&rsquo;s newest lands on the previous dimension&rsquo;s oldest),
          wrap behavior at the ends, empty dimensions absent from both the ring and the
          traversal, and the zero-breakthrough empty state. The merge also quietly
          resolved two open debates at once: it settled donut-vs-line-chart in the
          donut&rsquo;s favor (a clickable segmented ring earns its place as a filter),
          and because the filter is now <em>intra-widget</em>, it delivered the
          cross-filtering experience without violating the no-page-level-filters rule.
        </p>
        <VideoFrame
          title="The combined breakthrough widget"
          description="The two-mode state machine in action: Mode A walking the full history, then a segment click entering Mode B with the donut's live selection following auto-advance across dimension boundaries."
          src="/videos/my-world/breakthrough-widget.mp4"
          tone="pink"
        />

        <h3>Decluttering the topic surface</h3>
        <p>
          Through weekly design triage with the founder and stakeholders, I ran repeated
          simplification passes on the topic card and detail view: stripping section
          labels down to inline values (<code>Family · May 9 – May 30 · Active</code>),
          removing timestamps, showing the year only when it isn&rsquo;t the current one,
          renaming &ldquo;Archive&rdquo; to &ldquo;Box&rdquo; to fit the product&rsquo;s
          ontological language (with the icon arrow flipped to point <em>into</em> the
          box), and holding the line on sticky bottom CTAs — because users make their
          &ldquo;continue or close&rdquo; decision only <em>after</em> reading through a
          topic. Small calls individually; together they turned a dense admin panel into
          something that reads like a document.
        </p>

        <h3>The Reminders widget</h3>
        <p>
          When the team reframed <code>commitments</code> (concrete checkable tasks) into{" "}
          <code>reminders</code> (which can also be stances and ways of being —
          &ldquo;Notice the voice of fear and keep going anyway&rdquo;), I designed the
          widget that carries them: reminders pooled across all sessions, newest first,{" "}
          <strong>paginated inside the widget</strong> — never a separate page. Two
          actions: <strong>Done</strong> and <strong>Delete</strong> — Delete exists
          precisely because these are AI-generated and the AI can be wrong, so users need
          an honest way out. Both actions update shared state across the widget{" "}
          <em>and</em> the originating session view.
        </p>
        <p>
          One detail I&rsquo;m proud of: when a user un-checks a completed reminder, it{" "}
          <strong>re-enters at its original chronological position</strong>, not floated
          to the top. Position encodes creation order and is invariant to toggling — one
          rule, consistent across both surfaces. I flagged the engineering implication
          myself: since done items vanish from the widget, correct reinsertion requires
          storing the original creation timestamp in shared state, not deriving it from
          visible position. That note went straight into the build spec.
        </p>
        <VideoFrame
          title="Reminders widget interactions"
          description="Done, Delete, and in-widget pagination — including an un-checked reminder re-entering at its original chronological position."
          src="/videos/my-world/reminders-widget.mp4"
          tone="sky"
        />
        <p>
          The design is fully <strong>responsive</strong> — every widget, the topic list,
          and both detail views adapt from a 1440px desktop layout down to mobile,
          specced with breakpoint behavior rather than as two separate designs.
        </p>
      </CaseSection>

      <CaseSection
        id="ai"
        eyebrow="Layer 3 · The AI"
        title="Prompts, playgrounds, and QA"
      >
        <h3>Prompt engineering as design work</h3>
        <p>
          I wrote and iterated the prompts that generate everything on screen: the
          session summary (through six versions), the topic summary (through seven),
          topic detection, and the coaching invitation prompt. The craft here is closer
          to spec-writing than copywriting — every sentence must contain an executable
          instruction, and I learned the hard way that{" "}
          <strong>silence in a gate is an admission</strong>: if you don&rsquo;t
          explicitly name an exclusion with examples, the model will walk through it.
        </p>
        <p>
          The <code>breakthrough_insight</code> field is the best example. A breakthrough
          shown back to a user is a claim about their life — get it wrong and you
          manufacture a false memory. I built the field around a strict{" "}
          <strong>ownership gate</strong> (it only qualifies if the user explicitly said
          it or strongly agreed), a Promise/Declaration test, an explicit ban list for
          inceptive language (&ldquo;began to,&rdquo; &ldquo;starting to&rdquo; — a
          breakthrough is an arrival, not an intention), a ban on victory language
          (&ldquo;freedom from,&rdquo; &ldquo;dissolves its grip&rdquo;), and a required
          verb-first opener to kill stative constructions.
        </p>

        <h3>Building my own QA tooling</h3>
        <p>
          You can&rsquo;t QA a generative feature by eyeballing one output. I extended
          our <strong>Streamlit playground</strong> — a test harness that runs real
          conversation transcripts through the full pipeline and exports structured JSON
          — and specced a new Invitation tab (one new file, a five-line additive diff to
          the existing UI, shared helpers imported rather than duplicated) so I could
          tune the provocation prompt against real session objects with the context
          window size as the primary dial.
        </p>
        <ImageFrame
          alt="The Streamlit QA playground running a batch of real conversation transcripts through the generation pipeline"
          plannedSrc="/images/my-world/streamlit-playground.png"
          aspect="wide"
          tone="mint"
          caption="The Streamlit playground: real transcripts in, structured JSON out."
        />
        <p>
          My QA method: run a batch of ~20 sessions, then perform{" "}
          <strong>field-level compliance checks</strong> of every output against the
          prompt&rsquo;s own explicit rules. A recent run surfaced five must-fix issues —
          including the breakthrough gate passing two &ldquo;non-seeings,&rdquo; a
          near-verbatim use of banned psychological register, and a markdown artifact
          leaking into user-facing prose — each traced to a specific missing clause and
          fixed with a surgical prompt insert, not a rewrite.{" "}
          <TodoNote>optional: add hit-rate / accuracy numbers you&rsquo;re comfortable publishing</TodoNote>
        </p>
      </CaseSection>

      <CaseSection
        id="implementation"
        eyebrow="Co-implementation"
        title="From mockups to merge requests"
      >
        <p>
          Midway through the project I stopped ending my work at the Figma handoff. Using{" "}
          <strong>Claude Code</strong>, I began implementing widgets myself on localhost
          — <TodoNote>confirm stack detail: e.g., React + Tailwind on the shadcn-based Obra design system</TodoNote>{" "}
          — and shipping working builds directly to engineers for review{" "}
          <TodoNote>confirm detail: PRs / branch handoff to Maaz and Zain</TodoNote>.
        </p>
        <p>
          The technique that made this work: I write{" "}
          <strong>implementation prompts the way I write design specs.</strong> The
          combined breakthrough widget went to code as a complete state-machine prompt —
          both modes, all transitions, the traversal model, the edge cases, design
          tokens, and every assumption explicitly flagged as a one-line toggle if wrong.
          Ambiguity resolved before code, not during review.
        </p>
        <p>
          The payoff was speed: design questions that used to take a build-and-wait cycle
          now get answered the same afternoon, and engineers review a working reference
          instead of interpreting a static frame.{" "}
          <TodoNote>metric if usable: &ldquo;reduced design-to-review cycles from days to hours&rdquo;</TodoNote>
        </p>
        <p>
          I applied the same rigor to the design system itself: a seven-hue dimension
          palette (rose → fuchsia, one hue per color-wheel zone) with three semantic
          tokens per dimension referencing the brand layer — the same token order that
          drives the breakthrough widget&rsquo;s traversal logic, so the palette is a
          single source of truth for both visual identity and interaction behavior.
        </p>
      </CaseSection>

      <CaseSection id="outcomes" eyebrow="Status" title="Where it stands">
        <p>
          My World is <strong>live in development and actively shipping</strong> — the
          featured band, reminders widget, topic list, and detail views are implemented;
          the coaching invitation surface and mood taxonomy integration are in progress.{" "}
          <TodoNote>add outcome metrics here if available — e.g., retention movement, sessions processed</TodoNote>
        </p>
      </CaseSection>

      <CaseSection
        id="takeaway"
        eyebrow="Reflection"
        title="What I'd want a hiring team to take from this"
      >
        <p>
          I designed a novel AI product surface from architecture to pixels — but the
          thing I&rsquo;d point to is the shape of the work: I wrote the product doc
          engineers build from, the prompts that generate the content, the QA tooling
          that validates them, the specs that resolve edge cases before code, and
          increasingly the code itself.
        </p>
        <PullQuote>
          At a pre-seed startup, the most valuable designer is the one who removes
          handoffs. That&rsquo;s the designer I&rsquo;ve become — and the design engineer
          I&rsquo;m becoming.
        </PullQuote>
      </CaseSection>
    </CaseStudyLayout>
  );
}
